# Generated by Django 3.2 on 2021-05-24 14:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=30)),
                ('cantAsientos', models.PositiveIntegerField(default=0)),
                ('patente', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('Comodo', 'Cómodo'), ('SuperComodo', 'Súper Comodo')], default='Comodo', max_length=11)),
            ],
            options={
                'verbose_name': 'Combi',
                'verbose_name_plural': 'Combis',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('puntuacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('nombre', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.CharField(max_length=50)),
                ('precio', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
            },
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('nombre', models.CharField(max_length=30)),
                ('codigoPostal', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Lugar',
                'verbose_name_plural': 'Lugares',
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('distancia', models.PositiveIntegerField()),
                ('descripcion', models.CharField(max_length=50)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutaDestino', to='PaginaDePruebaApp.lugar')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutaOrigen', to='PaginaDePruebaApp.lugar')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
                'unique_together': {('origen', 'destino', 'descripcion')},
            },
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro', models.IntegerField()),
                ('fechaVto', models.DateTimeField()),
                ('codigo', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Tarjeta',
                'verbose_name_plural': 'Tarjetas',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('esCliente', models.BooleanField(default=False)),
                ('esChofer', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='PaginaDePruebaApp.user')),
                ('telefono', models.PositiveIntegerField(max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Chofer',
                'verbose_name_plural': 'Choferes',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='PaginaDePruebaApp.user')),
                ('dni', models.IntegerField(null=True)),
                ('suspendido', models.BooleanField(default=False)),
                ('esGold', models.BooleanField(default=False)),
                ('ahorro', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enCurso', models.BooleanField(default=False, verbose_name='Viaje iniciado')),
                ('finalizado', models.BooleanField(default=False, verbose_name='Viaje finalizado')),
                ('fechaSalida', models.DateTimeField()),
                ('fechaLlegada', models.DateTimeField()),
                ('duracion', models.CharField(default='', max_length=20)),
                ('precio', models.PositiveIntegerField()),
                ('combi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PaginaDePruebaApp.combi', verbose_name='Lista de combis')),
                ('insumo', models.ManyToManyField(blank=True, to='PaginaDePruebaApp.Insumo', verbose_name='Lista de insumos')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PaginaDePruebaApp.ruta', verbose_name='ruta')),
            ],
            options={
                'verbose_name': 'Viaje',
                'verbose_name_plural': 'Viajes',
            },
        ),
        migrations.CreateModel(
            name='Pasaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCompra', models.DateTimeField(auto_now_add=True)),
                ('total', models.FloatField()),
                ('comentario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PaginaDePruebaApp.comentario')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PaginaDePruebaApp.viaje')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PaginaDePruebaApp.cliente')),
            ],
            options={
                'verbose_name': 'Pasaje',
                'verbose_name_plural': 'Pasajes',
            },
        ),
        migrations.AddField(
            model_name='combi',
            name='chofer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='PaginaDePruebaApp.chofer'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='historialViajes',
            field=models.ManyToManyField(default=None, null=True, to='PaginaDePruebaApp.Viaje'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tarjeta',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='PaginaDePruebaApp.tarjeta'),
        ),
    ]
