# Generated by Django 3.2 on 2021-04-26 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaDePruebaApp', '0002_auto_20210425_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combi',
            name='marca',
        ),
    ]
