# Generated by Django 3.1.7 on 2021-04-23 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaDePruebaApp', '0002_insumo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Combi',
        ),
        migrations.DeleteModel(
            name='Insumo',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
