# Generated by Django 3.1.7 on 2021-04-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaDePruebaApp', '0003_remove_combi_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dni',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
