# Generated by Django 3.2 on 2021-05-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaDePruebaApp', '0003_auto_20210524_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasaje',
            name='cancelado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pasaje',
            name='insumos',
            field=models.ManyToManyField(default=None, null=True, to='PaginaDePruebaApp.Insumo'),
        ),
        migrations.AddField(
            model_name='pasaje',
            name='pendiente',
            field=models.BooleanField(default=True),
        ),
    ]
