# Generated by Django 3.1.7 on 2021-04-23 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaDePruebaApp', '0004_combi_insumo_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('contraseña', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='combi',
            name='chofer',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='PaginaDePruebaApp.chofer'),
            preserve_default=False,
        ),
    ]
