# Generated by Django 3.1.7 on 2021-04-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaDePruebaApp', '0004_user_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fechaDeNaciemiento',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
