# Generated by Django 3.1.7 on 2021-05-01 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaDePruebaApp', '0004_auto_20210430_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='PaginaDePruebaApp.user')),
                ('telefono', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
