# Generated by Django 3.2 on 2021-05-28 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaDePruebaApp', '0005_auto_20210526_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='invitados',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
