# Generated by Django 3.1.7 on 2021-04-23 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PaginaDePruebaApp', '0005_auto_20210423_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chofer',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='chofer',
            name='contraseña',
        ),
        migrations.RemoveField(
            model_name='chofer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='chofer',
            name='nombre',
        ),
        migrations.AddField(
            model_name='chofer',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
