# Generated by Django 3.2 on 2021-05-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaDePruebaApp', '0007_auto_20210501_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chofer',
            name='telefono',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
