# Generated by Django 3.2 on 2021-05-30 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaDePruebaApp', '0007_auto_20210528_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='comentario',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='PaginaDePruebaApp.comentario'),
        ),
    ]
