# Generated by Django 3.1.7 on 2021-04-23 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PaginaDePruebaApp', '0008_auto_20210423_0259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chofer',
            options={},
        ),
        migrations.AlterModelManagers(
            name='chofer',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='chofer',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='chofer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='chofer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='chofer',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='chofer',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='chofer',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='chofer',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='chofer',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='chofer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='chofer',
            name='password',
        ),
        migrations.RemoveField(
            model_name='chofer',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='chofer',
            name='username',
        ),
        migrations.AddField(
            model_name='chofer',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='combi',
            name='chofer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PaginaDePruebaApp.chofer'),
        ),
    ]
