# Generated by Django 3.2 on 2021-05-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaDePruebaApp', '0008_alter_compra_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='pendiente',
            field=models.BooleanField(default=False),
        ),
    ]
