# Generated by Django 3.1.7 on 2021-04-29 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaDePruebaApp', '0008_auto_20210426_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('puntuacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('codigoPostal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia', models.IntegerField()),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutaDestino', to='PaginaDePruebaApp.lugar')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutaOrigen', to='PaginaDePruebaApp.lugar')),
            ],
        ),
        migrations.AddField(
            model_name='combi',
            name='cantAsientosDisponibles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='ahorro',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='suspendido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='combi',
            name='cantAsientos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='combi',
            name='chofer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaSalida', models.DateTimeField()),
                ('fechaLlegada', models.DateTimeField()),
                ('duracion', models.TimeField()),
                ('precio', models.FloatField()),
                ('enCurso', models.BooleanField()),
                ('finalizado', models.BooleanField()),
                ('combi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PaginaDePruebaApp.combi')),
                ('insumo', models.ManyToManyField(to='PaginaDePruebaApp.Insumo')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PaginaDePruebaApp.ruta')),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro', models.IntegerField()),
                ('fechaVto', models.DateTimeField()),
                ('codigo', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pasaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.FloatField()),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PaginaDePruebaApp.viaje')),
            ],
        ),
    ]
