# Generated by Django 3.2 on 2021-05-02 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaDePruebaApp', '0009_auto_20210502_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combi',
            name='chofer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PaginaDePruebaApp.chofer'),
        ),
    ]
