# Generated by Django 3.2 on 2021-04-29 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaDePruebaApp', '0009_auto_20210428_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='lugar',
            name='id',
        ),
        migrations.AlterField(
            model_name='insumo',
            name='nombre',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='precio',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='codigoPostal',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='distancia',
            field=models.PositiveIntegerField(),
        ),
    ]
