# Generated by Django 3.2 on 2021-05-03 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaDePruebaApp', '0010_alter_combi_chofer'),
    ]

    operations = [
        migrations.AddField(
            model_name='combi',
            name='tipo',
            field=models.CharField(choices=[('Comodo', 'Cómodo'), ('SuperComodo', 'Súper Comodo')], default='Comodo', max_length=11),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='combi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PaginaDePruebaApp.combi', verbose_name='Lista de combis'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='insumo',
            field=models.ManyToManyField(blank=True, to='PaginaDePruebaApp.Insumo', verbose_name='Lista de insumos'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PaginaDePruebaApp.ruta', verbose_name='Lista de rutas'),
        ),
    ]
