# Generated by Django 3.2 on 2021-06-03 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaDePruebaApp', '0011_auto_20210531_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='CantidadInsumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PaginaDePruebaApp.compra')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PaginaDePruebaApp.insumo')),
            ],
        ),
        migrations.RemoveField(
            model_name='compra',
            name='insumos',
        ),
        migrations.AddField(
            model_name='compra',
            name='insumos',
            field=models.ManyToManyField(default=None, null=True, through='PaginaDePruebaApp.CantidadInsumo', to='PaginaDePruebaApp.Insumo'),
        ),
    ]
