# Generated by Django 3.2 on 2021-05-04 15:27

import PaginaDePruebaApp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaDePruebaApp', '0012_auto_20210503_2012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chofer',
            options={'verbose_name': 'Chofer', 'verbose_name_plural': 'Choferes'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='combi',
            options={'verbose_name': 'Combi', 'verbose_name_plural': 'Combis'},
        ),
        migrations.AlterModelOptions(
            name='insumo',
            options={'verbose_name': 'Insumo', 'verbose_name_plural': 'Insumos'},
        ),
        migrations.AlterModelOptions(
            name='lugar',
            options={'verbose_name': 'Lugar', 'verbose_name_plural': 'Lugares'},
        ),
        migrations.AlterModelOptions(
            name='pasaje',
            options={'verbose_name': 'Pasaje', 'verbose_name_plural': 'Pasajes'},
        ),
        migrations.AlterModelOptions(
            name='ruta',
            options={'verbose_name': 'Ruta', 'verbose_name_plural': 'Rutas'},
        ),
        migrations.AlterModelOptions(
            name='tarjeta',
            options={'verbose_name': 'Tarjeta', 'verbose_name_plural': 'Tarjetas'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='viaje',
            options={'verbose_name': 'Viaje', 'verbose_name_plural': 'Viajes'},
        ),
        migrations.AlterField(
            model_name='viaje',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[PaginaDePruebaApp.validators.validatePrecio]),
        ),
    ]
