# Generated by Django 3.2 on 2021-05-04 01:25

import PaginaDePruebaApp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaDePruebaApp', '0012_auto_20210503_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='fechaLlegada',
            field=models.DateTimeField(validators=[PaginaDePruebaApp.validators.validateFechaSalida]),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='fechaSalida',
            field=models.DateTimeField(validators=[PaginaDePruebaApp.validators.validateFechaSalida]),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[PaginaDePruebaApp.validators.validatePrecio]),
        ),
    ]
