# Generated by Django 3.2 on 2021-06-03 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaDePruebaApp', '0012_auto_20210603_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='cantidadinsumo',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
