# Generated by Django 3.2 on 2021-05-04 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaDePruebaApp', '0013_auto_20210503_2225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Chofer'},
        ),
    ]
