# Generated by Django 3.1.7 on 2021-05-05 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaDePruebaApp', '0013_auto_20210504_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combi',
            name='chofer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='PaginaDePruebaApp.chofer'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutaDestino', to='PaginaDePruebaApp.lugar'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutaOrigen', to='PaginaDePruebaApp.lugar'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='combi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PaginaDePruebaApp.combi', verbose_name='Lista de combis'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PaginaDePruebaApp.ruta', verbose_name='Lista de rutas'),
        ),
    ]
