# Generated by Django 3.2.2 on 2021-06-22 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaDePruebaApp', '0013_cantidadinsumo_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imprevisto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('resuelto', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tarjeta',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PaginaDePruebaApp.tarjeta'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='imprevisto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='PaginaDePruebaApp.imprevisto'),
        ),
    ]
