# Generated by Django 3.2.2 on 2021-06-23 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaDePruebaApp', '0014_auto_20210622_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='imprevisto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PaginaDePruebaApp.imprevisto'),
        ),
    ]
