# Generated by Django 3.2 on 2021-05-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaDePruebaApp', '0014_auto_20210504_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='enCurso',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='finalizado',
            field=models.BooleanField(),
        ),
    ]
