# Generated by Django 3.2 on 2021-05-04 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaDePruebaApp', '0014_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chofer',
            options={'verbose_name': 'Chofer', 'verbose_name_plural': 'Choferes'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='combi',
            options={'verbose_name': 'Combi', 'verbose_name_plural': 'Combis'},
        ),
        migrations.AlterModelOptions(
            name='insumo',
            options={'verbose_name': 'Insumo', 'verbose_name_plural': 'Insumos'},
        ),
        migrations.AlterModelOptions(
            name='lugar',
            options={'verbose_name': 'Lugar', 'verbose_name_plural': 'Lugares'},
        ),
        migrations.AlterModelOptions(
            name='pasaje',
            options={'verbose_name': 'Pasaje', 'verbose_name_plural': 'Pasajes'},
        ),
        migrations.AlterModelOptions(
            name='ruta',
            options={'verbose_name': 'Ruta', 'verbose_name_plural': 'Rutas'},
        ),
        migrations.AlterModelOptions(
            name='tarjeta',
            options={'verbose_name': 'Tarjeta', 'verbose_name_plural': 'Tarjetas'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='viaje',
            options={'verbose_name': 'Viaje', 'verbose_name_plural': 'Viajes'},
        ),
    ]
