# Generated by Django 3.2 on 2021-05-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaDePruebaApp', '0015_auto_20210505_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='enCurso',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='finalizado',
            field=models.NullBooleanField(),
        ),
    ]
