# Generated by Django 3.2 on 2021-05-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaDePruebaApp', '0016_auto_20210505_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='enCurso',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='finalizado',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
