# Generated by Django 3.2.2 on 2021-06-26 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaDePruebaApp', '0017_auto_20210624_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='imprevisto',
        ),
        migrations.AddField(
            model_name='imprevisto',
            name='viaje',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='PaginaDePruebaApp.viaje'),
            preserve_default=False,
        ),
    ]
