# Generated by Django 3.2 on 2021-05-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaDePruebaApp', '0017_auto_20210505_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='enCurso',
            field=models.BooleanField(default=False, verbose_name='Viaje iniciado'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='finalizado',
            field=models.BooleanField(default=False, verbose_name='Viaje finalizado'),
        ),
    ]
