# Generated by Django 3.2.2 on 2021-06-26 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaDePruebaApp', '0018_auto_20210626_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='imprevisto',
            name='chofer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='PaginaDePruebaApp.chofer'),
            preserve_default=False,
        ),
    ]
