# Generated by Django 3.2 on 2021-05-08 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaDePruebaApp', '0018_auto_20210505_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PaginaDePruebaApp.ruta', verbose_name='ruta'),
        ),
    ]
