# Generated by Django 3.2 on 2021-06-27 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaDePruebaApp', '0018_auto_20210626_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reembolso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dinero', models.IntegerField()),
                ('fecha', models.DateTimeField()),
                ('realizado', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PaginaDePruebaApp.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='reembolso',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='PaginaDePruebaApp.reembolso'),
        ),
    ]
