# Generated by Django 3.2 on 2021-06-27 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaDePruebaApp', '0019_auto_20210627_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reembolso',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
