# Generated by Django 3.2 on 2021-05-07 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaDePruebaApp', '0019_alter_viaje_ruta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViajeInsumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('insumo_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PaginaDePruebaApp.insumo')),
                ('viaje_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PaginaDePruebaApp.viaje')),
            ],
        ),
        migrations.AlterField(
            model_name='viaje',
            name='insumo',
            field=models.ManyToManyField(blank=True, through='PaginaDePruebaApp.ViajeInsumo', to='PaginaDePruebaApp.Insumo', verbose_name='Lista de insumos'),
        ),
    ]
