# Generated by Django 3.2.2 on 2021-06-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaDePruebaApp', '0019_imprevisto_chofer'),
    ]

    operations = [
        migrations.AddField(
            model_name='imprevisto',
            name='fecha',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
