# Generated by Django 3.1.7 on 2021-05-09 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaDePruebaApp', '0020_alter_ruta_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='precio',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='duracion',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='precio',
            field=models.PositiveIntegerField(),
        ),
    ]
