# Generated by Django 3.2 on 2021-05-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaDePruebaApp', '0020_auto_20210507_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='insumo',
            field=models.ManyToManyField(blank=True, to='PaginaDePruebaApp.Insumo', verbose_name='Lista de insumos'),
        ),
        migrations.DeleteModel(
            name='ViajeInsumo',
        ),
    ]
