# Generated by Django 3.2.2 on 2021-06-28 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaDePruebaApp', '0020_imprevisto_fecha'),
        ('PaginaDePruebaApp', '0021_alter_reembolso_user'),
    ]

    operations = [
    ]
