# Generated by Django 3.2 on 2021-05-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaDePruebaApp', '0021_auto_20210509_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='duracion',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
    ]
