# Generated by Django 3.2 on 2021-05-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaDePruebaApp', '0022_alter_viaje_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chofer',
            name='telefono',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
