# Generated by Django 3.2 on 2021-06-28 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaDePruebaApp', '0022_merge_0020_imprevisto_fecha_0021_alter_reembolso_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='historialViajes',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='testRealizado',
        ),
        migrations.RemoveField(
            model_name='invitado',
            name='testRealizado',
        ),
        migrations.CreateModel(
            name='TestRealizadoInvitado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testRealizado', models.BooleanField(default=False)),
                ('invitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PaginaDePruebaApp.invitado')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PaginaDePruebaApp.viaje')),
            ],
        ),
        migrations.CreateModel(
            name='TestRealizadoCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testRealizado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PaginaDePruebaApp.cliente')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PaginaDePruebaApp.viaje')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='testRealizado',
            field=models.ManyToManyField(default=None, null=True, through='PaginaDePruebaApp.TestRealizadoCliente', to='PaginaDePruebaApp.Viaje'),
        ),
        migrations.AddField(
            model_name='invitado',
            name='testRealizado',
            field=models.ManyToManyField(default=None, null=True, through='PaginaDePruebaApp.TestRealizadoInvitado', to='PaginaDePruebaApp.Viaje'),
        ),
    ]
