# Generated by Django 3.2.2 on 2021-06-29 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaDePruebaApp', '0024_alter_cliente_suspendido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitado',
            name='suspendido',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
