# Generated by Django 3.2 on 2021-05-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaDePruebaApp', '0024_alter_chofer_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='duracion',
            field=models.CharField(default='', max_length=20),
        ),
    ]
